import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const apiUrl = (process.env.NG_APP_API_URL ?? process.env.API_URL ?? '')
  .trim()
  .replace(/\/$/, '');

const __dirname = dirname(fileURLToPath(import.meta.url));
const target = join(__dirname, '..', 'src', 'app', 'core', 'api-base.ts');
const content =
  `// Generated by scripts/write-api-env.mjs at build time. Do not edit manually.\n` +
  `export const API_BASE_URL = '${apiUrl}';\n`;
writeFileSync(target, content, 'utf8');
console.log(
  'Wrote API base URL:',
  apiUrl || '(empty — relative URLs will go through the vercel.json proxy rewrites)'
);
