using System.Text;
using DeployAI.Core.Deployments.Graph;

namespace DeployAI.Core.Deployments.Generation;

/// <summary>
/// Renders a deployment graph as a Docker Compose deployment: the compose file, each built
/// node's Dockerfile, and an nginx config for every node acting as a reverse proxy — with the
/// proxy behavior (buffering, body size, websockets) read off the ProxyRoute edges rather
/// than baked into a template. Replaces the framework-keyed single-origin-compose scenario:
/// this class contains no framework names.
/// </summary>
public sealed class ComposeGenerator : IDeploymentGenerator
{
    public const string ComposeFileName = "docker-compose.coolify.yml";

    public string Target => "compose";

    public GeneratedArtifacts Generate(DeploymentGraph graph)
    {
        var files = new List<GeneratedArtifact>
        {
            new(ComposeFileName, RenderCompose(graph))
        };

        foreach (var node in graph.Services.Where(s => s.Source.IsBuilt))
        {
            var dockerfile = node.Source.Dockerfile;
            if (dockerfile?.Content is not null)
            {
                files.Add(new GeneratedArtifact(
                    CombinePath(node.Source.BuildContext!, "Dockerfile"),
                    dockerfile.Content));
            }

            if (node.Capabilities.HasCapability(ServiceCapability.ReverseProxy))
            {
                files.Add(new GeneratedArtifact(
                    CombinePath(node.Source.BuildContext!, "nginx.conf"),
                    RenderNginx(graph, node)));
            }
        }

        return new GeneratedArtifacts(files);
    }

    private static string RenderCompose(DeploymentGraph graph)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by DeployAI — one Docker Compose resource for the whole deployment.");
        builder.AppendLine("# No host ports: the platform's proxy (Traefik on Coolify) terminates TLS and");
        builder.AppendLine("# routes the domain to the ingress service. Env values come from the platform UI.");
        builder.AppendLine("services:");

        var volumes = new List<string>();

        foreach (var node in graph.Services.Where(s => s.Capabilities.IsDeployable()))
        {
            builder.AppendLine($"  {node.Id}:");

            if (node.Source.IsBuilt)
            {
                builder.AppendLine($"    build: ./{node.Source.BuildContext!.TrimStart('.', '/')}");
            }
            else if (node.Source.PrebuiltImage is not null)
            {
                builder.AppendLine($"    image: {node.Source.PrebuiltImage}");
            }

            AppendEnvironment(builder, graph, node);

            // Only the ingress-facing service is exposed; everything else stays on the
            // internal network, reachable by service name.
            if (graph.Ingress.Any(rule => string.Equals(rule.ServiceId, node.Id, StringComparison.OrdinalIgnoreCase)))
            {
                var port = node.Source.Dockerfile?.ExposedPort ?? node.ListenPorts.FirstOrDefault(80);
                builder.AppendLine("    expose:");
                builder.AppendLine($"      - \"{port}\"");
            }

            AppendVolumes(builder, node, volumes);
            AppendDependsOn(builder, graph, node);
            builder.AppendLine("    restart: unless-stopped");
            builder.AppendLine();
        }

        foreach (var resource in graph.Services.Where(s =>
                     !s.Capabilities.IsDeployable() && s.Source.PrebuiltImage is not null &&
                     (s.Capabilities.HasCapability(ServiceCapability.Database) ||
                      s.Capabilities.HasCapability(ServiceCapability.Cache))))
        {
            builder.AppendLine($"  {resource.Id}:");
            builder.AppendLine($"    image: {resource.Source.PrebuiltImage}");
            AppendVolumes(builder, resource, volumes);
            builder.AppendLine("    restart: unless-stopped");
            builder.AppendLine();
        }

        if (volumes.Count > 0)
        {
            builder.AppendLine("volumes:");
            foreach (var volume in volumes.Distinct(StringComparer.OrdinalIgnoreCase))
            {
                builder.AppendLine($"  {volume}:");
            }
        }

        return builder.ToString().TrimEnd() + "\n";
    }

    private static void AppendEnvironment(StringBuilder builder, DeploymentGraph graph, ServiceNode node)
    {
        // The node's own detected requirements plus the keys its wiring imposes, all sourced
        // from platform-provided values via ${VAR} interpolation.
        var keys = node.Env.Select(env => env.Name)
            .Concat(graph.EdgesFrom<ConnectsToEdge>(node.Id).SelectMany(edge => edge.EnvMapping.Keys))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (keys.Count == 0)
        {
            return;
        }

        builder.AppendLine("    environment:");
        foreach (var key in keys)
        {
            builder.AppendLine($"      - {key}=${{{key}}}");
        }
    }

    private static void AppendVolumes(StringBuilder builder, ServiceNode node, List<string> volumes)
    {
        if (node.VolumeMounts.Count == 0)
        {
            return;
        }

        builder.AppendLine("    volumes:");
        foreach (var mount in node.VolumeMounts)
        {
            builder.AppendLine($"      - {mount.Name}:{mount.MountPath}");
            volumes.Add(mount.Name);
        }
    }

    private static void AppendDependsOn(StringBuilder builder, DeploymentGraph graph, ServiceNode node)
    {
        var dependencies = graph.EdgesFrom<DependsOnEdge>(node.Id).ToList();
        if (dependencies.Count == 0)
        {
            return;
        }

        builder.AppendLine("    depends_on:");
        foreach (var edge in dependencies)
        {
            // HealthGated would render as `condition: service_healthy`, but that requires the
            // target to declare a healthcheck block; until healthchecks are emitted, a plain
            // dependency is honest — the stricter form would fail compose validation.
            builder.AppendLine($"      - {edge.ToServiceId}");
        }
    }

    private static string RenderNginx(DeploymentGraph graph, ServiceNode proxyNode)
    {
        var builder = new StringBuilder();
        builder.AppendLine("server {");
        builder.AppendLine("  listen 80;");
        builder.AppendLine("  server_name _;");
        builder.AppendLine("  root /usr/share/nginx/html;");
        builder.AppendLine("  index index.html;");
        builder.AppendLine();

        var routes = graph.EdgesFrom<ProxyRouteEdge>(proxyNode.Id).ToList();

        var maxBody = routes.Select(r => r.MaxBodySize).FirstOrDefault(v => !string.IsNullOrWhiteSpace(v));
        if (maxBody is not null)
        {
            builder.AppendLine("  # Matched to the app's own upload limit; nginx's 1m default rejects real uploads.");
            builder.AppendLine($"  client_max_body_size {maxBody};");
            builder.AppendLine();
        }

        foreach (var route in routes)
        {
            var target = graph.FindService(route.ToServiceId);
            var port = target?.Source.Dockerfile?.ExposedPort ?? target?.ListenPorts.FirstOrDefault(80) ?? 80;
            var prefix = "/" + route.PathPrefix.Trim('/');

            builder.AppendLine($"  # This route is what makes the deployment single-origin: the app calls");
            builder.AppendLine($"  # relative {prefix} paths and nginx forwards them over the compose network.");
            builder.AppendLine($"  location {prefix}/ {{");
            builder.AppendLine($"    proxy_pass http://{route.ToServiceId}:{port};");
            builder.AppendLine("    proxy_set_header Host $host;");
            builder.AppendLine("    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
            builder.AppendLine("    proxy_set_header X-Forwarded-Proto $scheme;");

            if (!route.RequestBuffering)
            {
                builder.AppendLine("    proxy_request_buffering off; # stream large uploads instead of spooling to disk");
            }

            if (route.WebSockets)
            {
                builder.AppendLine("    proxy_http_version 1.1;");
                builder.AppendLine("    proxy_set_header Upgrade $http_upgrade;");
                builder.AppendLine("    proxy_set_header Connection \"upgrade\";");
            }

            builder.AppendLine("  }");
            builder.AppendLine();
        }

        if (proxyNode.Capabilities.HasCapability(ServiceCapability.StaticSite))
        {
            builder.AppendLine("  # Build output is hash-named, so it can be cached forever.");
            builder.AppendLine("  location ~* \\.(?:js|css|woff2?)$ {");
            builder.AppendLine("    add_header Cache-Control \"public, max-age=31536000, immutable\" always;");
            builder.AppendLine("  }");
            builder.AppendLine();
            builder.AppendLine("  # SPA fallback; index.html revalidates so a stale copy can't pin an old build.");
            builder.AppendLine("  location / {");
            builder.AppendLine("    try_files $uri $uri/ /index.html;");
            builder.AppendLine("    add_header Cache-Control \"no-cache\" always;");
            builder.AppendLine("  }");
            builder.AppendLine();
        }

        builder.AppendLine("  gzip on;");
        builder.AppendLine("  gzip_types text/css application/javascript application/json image/svg+xml;");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string CombinePath(string context, string fileName)
    {
        var normalized = context.Trim().Trim('/');
        return string.IsNullOrEmpty(normalized) || normalized == "." ? fileName : $"{normalized}/{fileName}";
    }
}
