using System.Net.Http.Json;
using System.Text.Json.Serialization;
using DeployAI.Core.Exceptions;
using DeployAI.Core.Providers;

namespace DeployAI.Providers.Coolify;

public sealed partial class CoolifyProvider
{
    public async Task<ProviderProject> CreateProjectAsync(
        ProviderCredentials credentials,
        CreateProviderProjectRequest request,
        CancellationToken cancellationToken)
    {
        var session = CoolifyApiSupport.ParseSession(credentials);
        var projectUuid = await ResolveProjectUuidAsync(session, request, cancellationToken);
        var serverUuid = await ResolveServerUuidAsync(session, request, cancellationToken);
        var environment = await ResolveEnvironmentAsync(session, projectUuid, request, cancellationToken);
        var buildPack = CoolifyApiSupport.ResolveBuildPack(request);
        var gitRepository = CoolifyApiSupport.NormalizeGitHubRepoUrl(request.GitHubRepoFullName);
        var gitBranch = string.IsNullOrWhiteSpace(request.GitBranch) ? "main" : request.GitBranch.Trim();

        var isCompose = CoolifyApiSupport.IsComposeBuildPack(buildPack);

        var body = new Dictionary<string, object?>
        {
            ["project_uuid"] = projectUuid,
            ["server_uuid"] = serverUuid,
            ["environment_name"] = environment.Name,
            ["environment_uuid"] = environment.Uuid,
            ["git_repository"] = gitRepository,
            ["git_branch"] = gitBranch,
            ["build_pack"] = buildPack,
            ["name"] = request.Name.Trim(),
            // Deliberately deferred: the domain must be attached and read back before env vars
            // are written, because values like the public site URL *are* the final domain.
            ["instant_deploy"] = false
        };

        var exposedPort = CoolifyApiSupport.ResolveExposedPort(buildPack, request);
        if (exposedPort is not null)
        {
            body["ports_exposes"] = exposedPort;
        }

        // A caller-supplied domain replaces the autogenerated sslip.io hostname. Asking for
        // both makes Coolify generate one and then immediately overwrite it.
        if (string.IsNullOrWhiteSpace(request.CustomDomain))
        {
            body["autogenerate_domain"] = true;
        }

        if (isCompose)
        {
            body["docker_compose_location"] = NormalizeComposeLocation(request.ComposeFileLocation);
        }

        // Pushes to the deployment branch redeploy on their own. Without this the app only ever
        // updates when someone comes back to DeployAI and presses publish.
        body["is_auto_deploy_enabled"] = true;

        if (!string.IsNullOrWhiteSpace(request.RootDirectory) && !isCompose)
        {
            body["base_directory"] = request.RootDirectory;
        }

        // Compose builds its own images from per-service Dockerfiles, so publish_directory and
        // is_static describe a build Coolify is not running.
        if (!string.IsNullOrWhiteSpace(request.OutputDirectory) && !isCompose)
        {
            body["publish_directory"] = request.OutputDirectory;
            body["is_static"] = true;
        }

        if (!isCompose)
        {
            if (!string.IsNullOrWhiteSpace(request.BuildCommand))
            {
                body["build_command"] = request.BuildCommand;
            }

            if (!string.IsNullOrWhiteSpace(request.InstallCommand))
            {
                body["install_command"] = request.InstallCommand;
            }

            if (!string.IsNullOrWhiteSpace(request.StartCommand))
            {
                body["start_command"] = request.StartCommand;
            }

            if (!string.IsNullOrWhiteSpace(request.DockerfilePath))
            {
                body["dockerfile_location"] = request.DockerfilePath;
            }
        }

        string createPath;
        if (request.IsPrivateRepository)
        {
            var githubAppUuid = await ResolveGithubAppUuidAsync(session, request, cancellationToken);
            body["github_app_uuid"] = githubAppUuid;
            createPath = isCompose
                ? "applications/dockercompose-private-github-app"
                : "applications/private-github-app";
        }
        else
        {
            createPath = isCompose ? "applications/dockercompose" : "applications/public";
        }

        using var createRequest = CreateRequest(HttpMethod.Post, session, createPath);
        createRequest.Content = JsonContent.Create(body);
        var response = await _httpClient.SendAsync(createRequest, cancellationToken);
        var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);

        if (!response.IsSuccessStatusCode)
        {
            throw new DeployAIException(
                "coolify_api_error",
                CoolifyApiSupport.ParseErrorMessage(responseBody)
                    ?? $"Could not create Coolify application ({(int)response.StatusCode}).");
        }

        var created = await response.Content.ReadFromJsonAsync<CoolifyCreateApplicationResponse>(cancellationToken)
            ?? throw new InvalidOperationException("Coolify returned an empty application response.");

        if (string.IsNullOrWhiteSpace(created.Uuid))
        {
            throw new DeployAIException(
                "coolify_api_error",
                "Coolify did not return an application id.");
        }

        if (!string.IsNullOrWhiteSpace(request.CustomDomain))
        {
            await AssignDomainAsync(session, created.Uuid, request, isCompose, cancellationToken);
        }

        var application = await TryGetApplicationAsync(session, created.Uuid, cancellationToken);
        return new ProviderProject(
            created.Uuid,
            application?.Name ?? request.Name.Trim(),
            NormalizeUrl(application?.Fqdn),
            gitBranch);
    }

    /// <summary>
    /// Attaches the domain to the application, and for compose to a specific service. Without
    /// this, Traefik has no rule to route on and no certificate is issued — the deploy succeeds
    /// and the site is unreachable.
    /// </summary>
    private async Task AssignDomainAsync(
        CoolifyApiSupport.CoolifySession session,
        string applicationUuid,
        CreateProviderProjectRequest request,
        bool isCompose,
        CancellationToken cancellationToken)
    {
        var domain = NormalizeUrl(request.CustomDomain!)!;
        var body = new Dictionary<string, object?> { ["domains"] = domain };

        if (isCompose)
        {
            var serviceName = string.IsNullOrWhiteSpace(request.DomainServiceName)
                ? "web"
                : request.DomainServiceName.Trim();

            // Compose apps route per service: the domain belongs to the one service that faces
            // the browser, and everything else stays on the internal network.
            body["docker_compose_domains"] = new Dictionary<string, object?>
            {
                [serviceName] = new { domain }
            };
        }
        else
        {
            body["fqdn"] = domain;
        }

        using var patchRequest = CreateRequest(HttpMethod.Patch, session, $"applications/{applicationUuid}");
        patchRequest.Content = JsonContent.Create(body);
        var response = await _httpClient.SendAsync(patchRequest, cancellationToken);
        var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);

        if (!response.IsSuccessStatusCode)
        {
            throw new DeployAIException(
                "coolify_domain_failed",
                CoolifyApiSupport.ParseErrorMessage(responseBody)
                    ?? $"Could not attach {domain} to the Coolify application ({(int)response.StatusCode}).");
        }
    }

    /// <summary>
    /// Coolify resolves this against the repository root and rejects a leading slash.
    /// </summary>
    private static string NormalizeComposeLocation(string? location)
    {
        var trimmed = location?.Trim().Replace('\\', '/').TrimStart('/');
        return string.IsNullOrWhiteSpace(trimmed) ? "docker-compose.yml" : trimmed;
    }

    public async Task<IReadOnlyList<ProviderEnvVar>> ListEnvVarsAsync(
        ProviderCredentials credentials,
        string providerProjectId,
        CancellationToken cancellationToken)
    {
        var session = CoolifyApiSupport.ParseSession(credentials);
        using var request = CreateRequest(HttpMethod.Get, session, $"applications/{providerProjectId}/envs");
        var response = await _httpClient.SendAsync(request, cancellationToken);
        var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);

        if (!response.IsSuccessStatusCode)
        {
            throw new DeployAIException(
                "coolify_api_error",
                CoolifyApiSupport.ParseErrorMessage(responseBody)
                    ?? $"Could not list Coolify environment variables ({(int)response.StatusCode}).");
        }

        var envs = await response.Content.ReadFromJsonAsync<List<CoolifyEnvironmentVariable>>(cancellationToken) ?? [];
        return envs
            .Where(env => !string.IsNullOrWhiteSpace(env.Key))
            .Select(env => new ProviderEnvVar(
                env.Uuid ?? env.Key!,
                env.Key!,
                env.IsShownOnce == true ? null : env.Value,
                "plain",
                [],
                env.IsShownOnce == true))
            .OrderBy(env => env.Key, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    public async Task<ProviderEnvVar> UpsertEnvVarAsync(
        ProviderCredentials credentials,
        string providerProjectId,
        UpsertProviderEnvVarRequest request,
        CancellationToken cancellationToken)
    {
        var session = CoolifyApiSupport.ParseSession(credentials);
        var existing = await ListEnvVarsAsync(credentials, providerProjectId, cancellationToken);
        var match = existing.FirstOrDefault(env =>
            string.Equals(env.Key, request.Key, StringComparison.OrdinalIgnoreCase));

        if (match is not null)
        {
            using var patchRequest = CreateRequest(HttpMethod.Patch, session, $"applications/{providerProjectId}/envs");
            patchRequest.Content = JsonContent.Create(BuildEnvVarPayload(request));
            var patchResponse = await _httpClient.SendAsync(patchRequest, cancellationToken);
            var patchBody = await patchResponse.Content.ReadAsStringAsync(cancellationToken);
            if (!patchResponse.IsSuccessStatusCode)
            {
                throw new DeployAIException(
                    "coolify_api_error",
                    CoolifyApiSupport.ParseErrorMessage(patchBody)
                        ?? $"Could not update Coolify environment variable ({(int)patchResponse.StatusCode}).");
            }

            var updated = await patchResponse.Content.ReadFromJsonAsync<CoolifyEnvironmentVariable>(cancellationToken);
            return new ProviderEnvVar(
                updated?.Uuid ?? match.Id,
                request.Key,
                null,
                request.Type,
                request.Targets.ToList(),
                true);
        }

        using var createRequest = CreateRequest(HttpMethod.Post, session, $"applications/{providerProjectId}/envs");
        createRequest.Content = JsonContent.Create(BuildEnvVarPayload(request));
        var createResponse = await _httpClient.SendAsync(createRequest, cancellationToken);
        var createBody = await createResponse.Content.ReadAsStringAsync(cancellationToken);
        if (!createResponse.IsSuccessStatusCode)
        {
            throw new DeployAIException(
                "coolify_api_error",
                CoolifyApiSupport.ParseErrorMessage(createBody)
                    ?? $"Could not create Coolify environment variable ({(int)createResponse.StatusCode}).");
        }

        var created = await createResponse.Content.ReadFromJsonAsync<CoolifyEnvironmentVariable>(cancellationToken)
            ?? throw new InvalidOperationException("Coolify returned an empty env var response.");

        return new ProviderEnvVar(
            created.Uuid ?? request.Key,
            request.Key,
            null,
            request.Type,
            request.Targets.ToList(),
            created.IsShownOnce == true);
    }

    /// <summary>
    /// The Type and Targets on the request used to be accepted and silently dropped, so a
    /// secret landed in Coolify as a readable plain value and a build-time variable was never
    /// available to the image build.
    /// </summary>
    private static Dictionary<string, object?> BuildEnvVarPayload(UpsertProviderEnvVarRequest request)
    {
        var payload = new Dictionary<string, object?>
        {
            ["key"] = request.Key,
            ["value"] = request.Value,
            // Coolify interpolates unescaped values; literal keeps $ and {} intact, which
            // matters for generated keys and passwords.
            ["is_literal"] = true,
            ["is_multiline"] = request.Value.Contains('\n')
        };

        if (ProviderEnvVarTypes.IsBuildTime(request.Type))
        {
            payload["is_build_time"] = true;
        }

        if (ProviderEnvVarTypes.IsSecret(request.Type))
        {
            payload["is_shown_once"] = true;
        }

        if (request.Targets.Any(target => string.Equals(target, "preview", StringComparison.OrdinalIgnoreCase)))
        {
            payload["is_preview"] = true;
        }

        return payload;
    }

    public async Task DeleteEnvVarAsync(
        ProviderCredentials credentials,
        string providerProjectId,
        string envVarId,
        CancellationToken cancellationToken)
    {
        var session = CoolifyApiSupport.ParseSession(credentials);
        using var request = CreateRequest(
            HttpMethod.Delete,
            session,
            $"applications/{providerProjectId}/envs/{envVarId}");
        var response = await _httpClient.SendAsync(request, cancellationToken);
        var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);

        if (!response.IsSuccessStatusCode)
        {
            throw new DeployAIException(
                "coolify_api_error",
                CoolifyApiSupport.ParseErrorMessage(responseBody)
                    ?? $"Could not delete Coolify environment variable ({(int)response.StatusCode}).");
        }
    }

    public async Task DeleteProjectAsync(
        ProviderCredentials credentials,
        string providerProjectId,
        CancellationToken cancellationToken)
    {
        var session = CoolifyApiSupport.ParseSession(credentials);
        using var request = CreateRequest(HttpMethod.Delete, session, $"applications/{providerProjectId}");
        var response = await _httpClient.SendAsync(request, cancellationToken);
        var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);

        if (!response.IsSuccessStatusCode)
        {
            throw new DeployAIException(
                "coolify_api_error",
                CoolifyApiSupport.ParseErrorMessage(responseBody)
                    ?? $"Could not delete Coolify application ({(int)response.StatusCode}).");
        }
    }

    public async Task<CoolifyInfrastructureSnapshot> ListInfrastructureAsync(
        ProviderCredentials credentials,
        CancellationToken cancellationToken)
    {
        var session = CoolifyApiSupport.ParseSession(credentials);
        var projects = await ListCoolifyProjectsAsync(session, cancellationToken);
        var servers = await ListCoolifyServersAsync(session, cancellationToken);
        var githubApps = await ListCoolifyGithubAppsAsync(session, cancellationToken);
        return new CoolifyInfrastructureSnapshot(
            projects.Select(MapInfrastructureResource).ToList(),
            servers.Select(MapInfrastructureResource).ToList(),
            githubApps.Select(MapInfrastructureResource).ToList());
    }

    public async Task<IReadOnlyList<CoolifyInfrastructureResource>> ListProjectEnvironmentsAsync(
        ProviderCredentials credentials,
        string projectUuid,
        CancellationToken cancellationToken)
    {
        var session = CoolifyApiSupport.ParseSession(credentials);
        var environments = await ListCoolifyEnvironmentsAsync(session, projectUuid, cancellationToken);
        return environments
            .Select(env => new CoolifyInfrastructureResource(env.Uuid, env.Name))
            .ToList();
    }

    private async Task<string> ResolveProjectUuidAsync(
        CoolifyApiSupport.CoolifySession session,
        CreateProviderProjectRequest request,
        CancellationToken cancellationToken)
    {
        if (!string.IsNullOrWhiteSpace(request.CoolifyProjectUuid))
        {
            return request.CoolifyProjectUuid;
        }

        var projects = await ListCoolifyProjectsAsync(session, cancellationToken);
        if (projects.Count == 1)
        {
            return projects[0].Uuid;
        }

        // Taking [0] out of several was fine for a demo, wrong for the default production
        // target — it silently drops the app into whichever project Coolify happened to list
        // first. Make the caller choose instead.
        if (projects.Count > 1)
        {
            throw new DeployAIException(
                "coolify_project_ambiguous",
                "Your Coolify instance has more than one project. Pick which one to deploy into: " +
                string.Join(", ", projects.Select(project => project.Name)));
        }

        using var createRequest = CreateRequest(HttpMethod.Post, session, "projects");
        createRequest.Content = JsonContent.Create(new { name = request.Name.Trim() });
        var response = await _httpClient.SendAsync(createRequest, cancellationToken);
        var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            throw new DeployAIException(
                "coolify_api_error",
                CoolifyApiSupport.ParseErrorMessage(responseBody)
                    ?? $"Could not create Coolify project ({(int)response.StatusCode}).");
        }

        var created = await response.Content.ReadFromJsonAsync<CoolifyUuidResponse>(cancellationToken);
        if (string.IsNullOrWhiteSpace(created?.Uuid))
        {
            throw new DeployAIException(
                "coolify_api_error",
                "Coolify did not return a project id.");
        }

        return created.Uuid;
    }

    private async Task<string> ResolveServerUuidAsync(
        CoolifyApiSupport.CoolifySession session,
        CreateProviderProjectRequest request,
        CancellationToken cancellationToken)
    {
        if (!string.IsNullOrWhiteSpace(request.CoolifyServerUuid))
        {
            return request.CoolifyServerUuid;
        }

        var servers = await ListCoolifyServersAsync(session, cancellationToken);
        if (servers.Count == 0)
        {
            throw new DeployAIException(
                "coolify_no_server",
                "No servers are configured in your Coolify instance. Add a server in Coolify first.");
        }

        if (servers.Count > 1)
        {
            throw new DeployAIException(
                "coolify_server_ambiguous",
                "Your Coolify instance has more than one server. Pick which one to deploy to: " +
                string.Join(", ", servers.Select(server => server.Name)));
        }

        return servers[0].Uuid;
    }

    private async Task<CoolifyEnvironmentOption> ResolveEnvironmentAsync(
        CoolifyApiSupport.CoolifySession session,
        string projectUuid,
        CreateProviderProjectRequest request,
        CancellationToken cancellationToken)
    {
        var environments = await ListCoolifyEnvironmentsAsync(session, projectUuid, cancellationToken);
        if (environments.Count == 0)
        {
            throw new DeployAIException(
                "coolify_no_environment",
                "No environments are configured for the selected Coolify project.");
        }

        if (!string.IsNullOrWhiteSpace(request.CoolifyEnvironmentName))
        {
            var match = environments.FirstOrDefault(env =>
                string.Equals(env.Name, request.CoolifyEnvironmentName, StringComparison.OrdinalIgnoreCase) ||
                string.Equals(env.Uuid, request.CoolifyEnvironmentName, StringComparison.OrdinalIgnoreCase));
            if (match is not null)
            {
                return match;
            }
        }

        return environments.FirstOrDefault(env =>
                   string.Equals(env.Name, "production", StringComparison.OrdinalIgnoreCase))
               ?? environments[0];
    }

    private async Task<string> ResolveGithubAppUuidAsync(
        CoolifyApiSupport.CoolifySession session,
        CreateProviderProjectRequest request,
        CancellationToken cancellationToken)
    {
        if (!string.IsNullOrWhiteSpace(request.CoolifyGithubAppUuid))
        {
            return request.CoolifyGithubAppUuid;
        }

        var githubApps = await ListCoolifyGithubAppsAsync(session, cancellationToken);
        if (githubApps.Count == 0)
        {
            throw new DeployAIException(
                "coolify_no_github_app",
                "Private repositories require a GitHub App configured in Coolify. Set one up in Coolify → Sources → GitHub Apps.");
        }

        if (githubApps.Count > 1)
        {
            throw new DeployAIException(
                "coolify_github_app_required",
                "Choose which Coolify GitHub App to use for this private repository.");
        }

        return githubApps[0].Uuid;
    }

    private async Task<CoolifyApplication?> TryGetApplicationAsync(
        CoolifyApiSupport.CoolifySession session,
        string applicationUuid,
        CancellationToken cancellationToken)
    {
        using var request = CreateRequest(HttpMethod.Get, session, $"applications/{applicationUuid}");
        var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            return null;
        }

        return await response.Content.ReadFromJsonAsync<CoolifyApplication>(cancellationToken);
    }

    private async Task<IReadOnlyList<CoolifyNamedResource>> ListCoolifyProjectsAsync(
        CoolifyApiSupport.CoolifySession session,
        CancellationToken cancellationToken)
    {
        using var request = CreateRequest(HttpMethod.Get, session, "projects");
        var response = await _httpClient.SendAsync(request, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken, "Could not list Coolify projects.");
        var projects = await response.Content.ReadFromJsonAsync<List<CoolifyNamedResource>>(cancellationToken) ?? [];
        return projects.Where(project => !string.IsNullOrWhiteSpace(project.Uuid)).ToList();
    }

    private async Task<IReadOnlyList<CoolifyNamedResource>> ListCoolifyServersAsync(
        CoolifyApiSupport.CoolifySession session,
        CancellationToken cancellationToken)
    {
        using var request = CreateRequest(HttpMethod.Get, session, "servers");
        var response = await _httpClient.SendAsync(request, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken, "Could not list Coolify servers.");
        var servers = await response.Content.ReadFromJsonAsync<List<CoolifyNamedResource>>(cancellationToken) ?? [];
        return servers.Where(server => !string.IsNullOrWhiteSpace(server.Uuid)).ToList();
    }

    private async Task<IReadOnlyList<CoolifyNamedResource>> ListCoolifyGithubAppsAsync(
        CoolifyApiSupport.CoolifySession session,
        CancellationToken cancellationToken)
    {
        using var request = CreateRequest(HttpMethod.Get, session, "github-apps");
        var response = await _httpClient.SendAsync(request, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken, "Could not list Coolify GitHub apps.");
        var githubApps = await response.Content.ReadFromJsonAsync<List<CoolifyNamedResource>>(cancellationToken) ?? [];
        return githubApps.Where(app => !string.IsNullOrWhiteSpace(app.Uuid)).ToList();
    }

    private async Task<IReadOnlyList<CoolifyEnvironmentOption>> ListCoolifyEnvironmentsAsync(
        CoolifyApiSupport.CoolifySession session,
        string projectUuid,
        CancellationToken cancellationToken)
    {
        using var request = CreateRequest(HttpMethod.Get, session, $"projects/{projectUuid}/environments");
        var response = await _httpClient.SendAsync(request, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken, "Could not list Coolify environments.");
        var environments = await response.Content.ReadFromJsonAsync<List<CoolifyEnvironmentOption>>(cancellationToken) ?? [];
        return environments
            .Where(env => !string.IsNullOrWhiteSpace(env.Uuid) && !string.IsNullOrWhiteSpace(env.Name))
            .ToList();
    }

    private static async Task EnsureSuccessAsync(
        HttpResponseMessage response,
        CancellationToken cancellationToken,
        string fallbackMessage)
    {
        if (response.IsSuccessStatusCode)
        {
            return;
        }

        var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);
        throw new DeployAIException(
            "coolify_api_error",
            CoolifyApiSupport.ParseErrorMessage(responseBody) ?? fallbackMessage);
    }

    private static CoolifyInfrastructureResource MapInfrastructureResource(CoolifyNamedResource resource) =>
        new(
            resource.Uuid,
            string.IsNullOrWhiteSpace(resource.Name) ? resource.Uuid : resource.Name);

    private sealed class CoolifyCreateApplicationResponse
    {
        [JsonPropertyName("uuid")]
        public string? Uuid { get; set; }
    }

    private sealed class CoolifyUuidResponse
    {
        [JsonPropertyName("uuid")]
        public string? Uuid { get; set; }
    }

    private sealed class CoolifyEnvironmentVariable
    {
        [JsonPropertyName("uuid")]
        public string? Uuid { get; set; }

        [JsonPropertyName("key")]
        public string? Key { get; set; }

        [JsonPropertyName("value")]
        public string? Value { get; set; }

        [JsonPropertyName("is_shown_once")]
        public bool? IsShownOnce { get; set; }
    }

    internal sealed class CoolifyNamedResource
    {
        [JsonPropertyName("uuid")]
        public string Uuid { get; set; } = string.Empty;

        [JsonPropertyName("name")]
        public string? Name { get; set; }
    }

    private sealed class CoolifyEnvironmentOption
    {
        [JsonPropertyName("uuid")]
        public string Uuid { get; set; } = string.Empty;

        [JsonPropertyName("name")]
        public string Name { get; set; } = string.Empty;
    }
}
