using DeployAI.Core.Deployments.Graph;
using DeployAI.Core.Deployments.Graph.Transforms;
using DeployAI.Core.Deployments.Planning;

namespace DeployAI.Tests.Graph;

public class CoolifyComposePlannerTests
{
    private static DeploymentGraph YemenBreezeShapedGraph(string? domain = "breeze.example.com")
    {
        var web = new ServiceNode(
            "web", ServiceCapability.StaticSite, ServiceSource.FromBuild("client"), Framework: "angular");
        var api = new ServiceNode(
            "api", ServiceCapability.HttpService, ServiceSource.FromBuild("server/Api"), Framework: "dotnet",
            EnvRequirements:
            [
                new DetectedEnvVar("JWT_KEY", IsSecret: true),
                new DetectedEnvVar("ADMIN_EMAIL", IsSecret: false)
            ]);

        return SingleOriginTransform.Apply(
            new DeploymentGraph([web, api], [], []),
            new SingleOriginTransform.Options(Domain: domain));
    }

    // The ordering proven against a live instance: env before the first deploy (the app must
    // boot configured), domain after it (docker_compose_domains needs docker_compose_raw,
    // which only a deploy populates), then a redeploy to materialize the route.
    [Fact]
    public void Plan_EmitsTheProvenOrdering_ForAFreshDeployment()
    {
        var plan = new CoolifyComposePlanner().Plan(YemenBreezeShapedGraph(), ProviderStateSnapshot.Fresh);

        var kinds = plan.Steps.Select(s => s.GetType().Name).ToArray();
        Assert.Equal(
            ["EnsureApplicationStep", "SetEnvVarsStep", "DeployStep", "AssignDomainStep", "DeployStep"],
            kinds);

        Assert.False(((EnsureApplicationStep)plan.Steps[0]).Reuse);
        Assert.Equal(1, ((DeployStep)plan.Steps[2]).Ordinal);
        Assert.Equal(2, ((DeployStep)plan.Steps[4]).Ordinal);

        var env = (SetEnvVarsStep)plan.Steps[1];
        Assert.Contains("JWT_KEY", env.Keys);

        // Env strictly precedes the first deploy; the domain strictly follows it.
        Assert.True(kinds.ToList().IndexOf("SetEnvVarsStep") < kinds.ToList().IndexOf("DeployStep"));
    }

    [Fact]
    public void Plan_FlipsToReuse_WhenTheApplicationAlreadyExists()
    {
        var plan = new CoolifyComposePlanner().Plan(
            YemenBreezeShapedGraph(),
            new ProviderStateSnapshot(ApplicationExists: true));

        Assert.True(((EnsureApplicationStep)plan.Steps[0]).Reuse);
    }

    // A redeploy exists only to materialize a newly-assigned domain. Already assigned (or no
    // custom domain at all) means one deploy, not two.
    [Fact]
    public void Plan_SkipsTheDomainTail_WhenAlreadyAssigned()
    {
        var plan = new CoolifyComposePlanner().Plan(
            YemenBreezeShapedGraph(),
            new ProviderStateSnapshot(ApplicationExists: true, DomainAssigned: true));

        Assert.DoesNotContain(plan.Steps, s => s is AssignDomainStep);
        Assert.Single(plan.Steps.OfType<DeployStep>());
    }

    [Fact]
    public void Plan_SkipsTheDomainTail_ForAutogeneratedDomains()
    {
        var plan = new CoolifyComposePlanner().Plan(
            YemenBreezeShapedGraph(domain: null),
            ProviderStateSnapshot.Fresh);

        Assert.DoesNotContain(plan.Steps, s => s is AssignDomainStep);
        Assert.Single(plan.Steps.OfType<DeployStep>());
    }

    [Fact]
    public void Plan_ProvisionsBucketsBeforeTheApplication_AndReusesOwnedOnes()
    {
        var graph = YemenBreezeShapedGraph()
            .WithService(new ServiceNode(
                "media", ServiceCapability.ObjectStorage, ServiceSource.FromImage("s3")));

        var fresh = new CoolifyComposePlanner().Plan(graph, ProviderStateSnapshot.Fresh);
        var owned = new CoolifyComposePlanner().Plan(
            graph, new ProviderStateSnapshot(ExistingBuckets: ["media"]));

        // Bucket keys are among the env values the app needs at first boot, so the bucket
        // must exist before env is written.
        Assert.IsType<ProvisionBucketStep>(fresh.Steps[0]);
        Assert.False(((ProvisionBucketStep)fresh.Steps[0]).Reuse);
        Assert.True(((ProvisionBucketStep)owned.Steps[0]).Reuse);
    }

    // ConnectsTo env keys (db connection strings, storage keys) join the node's own detected
    // requirements in the SetEnvVars step — the executor needs the full key set in one place.
    [Fact]
    public void Plan_IncludesWiringKeys_InTheEnvStep()
    {
        var graph = YemenBreezeShapedGraph();
        var api = graph.FindService("api")!;
        graph = graph
            .WithService(new ServiceNode("db", ServiceCapability.Database, ServiceSource.FromImage("postgres:16")))
            .WithEdge(new ConnectsToEdge(
                api.Id, "db",
                new Dictionary<string, string> { ["ConnectionStrings__Default"] = "connection-string" },
                ConnectionCredentialKind.ConnectionString));

        var plan = new CoolifyComposePlanner().Plan(graph, ProviderStateSnapshot.Fresh);

        var env = plan.Steps.OfType<SetEnvVarsStep>().Single(s => s.ServiceId == "api");
        Assert.Contains("ConnectionStrings__Default", env.Keys);
        Assert.Contains("JWT_KEY", env.Keys);
    }
}
