using System.Text.RegularExpressions;

namespace DeployAI.Infrastructure.Adapters;

/// <summary>
/// Generates a Dockerfile for an ASP.NET Core server that Coolify's Nixpacks can't build:
/// a modular monolith whose entry project references sibling projects, and/or a .NET version
/// newer than the SDK Nixpacks ships. The build context is the build root (the parent that
/// holds every referenced project), <c>COPY . .</c> brings them all in, and publish targets the
/// entry csproj by its path relative to that root — the shape a modular solution needs and the
/// one <c>COPY *.csproj . &amp;&amp; dotnet publish</c> (a single-project assumption) gets wrong.
/// </summary>
public static class DotnetServerDockerfile
{
    /// <summary>The ASP.NET Core in-container default, and the port Coolify's proxy routes to.</summary>
    public const int ContainerPort = 8080;

    /// <summary>
    /// The migration executable copied into the runtime image. Named for its origin so it is
    /// obvious in a container listing that DeployAI put it there.
    /// </summary>
    public const string MigrationBundleName = "deployai-migrate";

    /// <summary>
    /// <paramref name="buildRootDirectory"/> is the Docker build context (Coolify base directory).
    /// <paramref name="serviceDirectory"/> is where the entry csproj lives; when it is nested under
    /// the build root (a modular monolith), the publish path is made relative to the root.
    /// </summary>
    public static string Build(
        string buildRootDirectory,
        string serviceDirectory,
        string? csprojContent,
        string csprojFileName)
    {
        var major = ResolveTargetFrameworkMajor(csprojContent) ?? 8;
        var assemblyName = Path.GetFileNameWithoutExtension(csprojFileName);
        var relativeProjectDir = RelativePath(buildRootDirectory, serviceDirectory);
        var csprojPath = string.IsNullOrEmpty(relativeProjectDir)
            ? csprojFileName
            : $"{relativeProjectDir}/{csprojFileName}";

        return $$"""
            # Generated by DeployAI. The build context is this directory so the sibling projects the
            # API references are all present; publish targets the API project by its relative path.
            FROM mcr.microsoft.com/dotnet/sdk:{{major}}.0 AS build
            WORKDIR /src
            COPY . .
            RUN dotnet publish {{csprojPath}} -c Release -o /app

            # A provisioned database starts empty, and nothing else in the pipeline creates its
            # schema -- an app deployed against one runs and fails every query on a missing table.
            # `migrations bundle` produces a standalone executable that applies them using the app's
            # own configuration, so the runtime image needs no SDK. Best effort: a project with no
            # DbContext or no migrations is not an error, it just has nothing to bundle.
            RUN dotnet tool install --global dotnet-ef --version {{major}}.* \
             && export PATH="$PATH:/root/.dotnet/tools" \
             && dotnet ef migrations bundle --startup-project {{csprojPath}} --configuration Release --force --output /app/{{MigrationBundleName}} \
             || echo "DeployAI: no EF migrations to bundle; the app will start without applying any."

            FROM mcr.microsoft.com/dotnet/aspnet:{{major}}.0
            # Npgsql loads GSSAPI when it opens a connection, and the ASP.NET runtime image does not
            # ship it. Without this every Postgres query fails with "libgssapi_krb5.so.2: cannot open
            # shared object file" -- from an app that started cleanly and looks healthy, because the
            # failure is per-request rather than at boot.
            RUN apt-get update \
             && apt-get install -y --no-install-recommends libgssapi-krb5-2 \
             && rm -rf /var/lib/apt/lists/*
            WORKDIR /app
            COPY --from=build /app .
            ENV ASPNETCORE_URLS=http://+:{{ContainerPort}}
            EXPOSE {{ContainerPort}}
            # Migrations run before the app, and a failure stops the container rather than letting it
            # serve against a half-built schema -- a running app with a broken database looks healthy
            # from every angle except the responses.
            ENTRYPOINT ["/bin/sh", "-c", "if [ -x ./{{MigrationBundleName}} ]; then ./{{MigrationBundleName}} || exit 1; fi; exec dotnet {{assemblyName}}.dll"]
            """;
    }

    /// <summary>Reads net8.0 / net10.0 from the csproj so the image tags match the code's runtime.</summary>
    public static int? ResolveTargetFrameworkMajor(string? csprojContent)
    {
        if (string.IsNullOrWhiteSpace(csprojContent))
        {
            return null;
        }

        var match = Regex.Match(
            csprojContent,
            @"<TargetFramework>\s*net(\d+)\.\d+\s*</TargetFramework>",
            RegexOptions.IgnoreCase);

        return match.Success && int.TryParse(match.Groups[1].Value, out var major) ? major : null;
    }

    private static string RelativePath(string root, string full)
    {
        var normalizedRoot = Normalize(root);
        var normalizedFull = Normalize(full);
        if (string.IsNullOrEmpty(normalizedRoot))
        {
            return normalizedFull;
        }

        if (normalizedFull.Equals(normalizedRoot, StringComparison.OrdinalIgnoreCase))
        {
            return string.Empty;
        }

        return normalizedFull.StartsWith(normalizedRoot + "/", StringComparison.OrdinalIgnoreCase)
            ? normalizedFull[(normalizedRoot.Length + 1)..]
            : normalizedFull;
    }

    private static string Normalize(string? path) =>
        path?.Trim().Replace('\\', '/').Trim('/') ?? string.Empty;
}
