using System.Text;
using System.Text.RegularExpressions;

namespace DeployAI.Infrastructure.Adapters;

/// <summary>
/// Generates a Dockerfile for a server-rendered JavaScript frontend (Next.js, Nuxt, SvelteKit,
/// Remix) that Coolify's Nixpacks build pack cannot configure correctly.
/// <para>
/// The reason this exists rather than letting Nixpacks handle it: Coolify only passes its own
/// <c>NIXPACKS_*</c> and <c>COOLIFY_*</c> variables to a Nixpacks build, never the application's
/// environment. Frameworks in this family compile public values into the bundle at build time
/// (Next.js inlines <c>NEXT_PUBLIC_*</c>, Vite <c>VITE_*</c>), so the build silently bakes in
/// whatever the source's fallback is — typically a localhost URL — and the deployed site then
/// calls the developer's machine. Owning the Dockerfile lets those values be declared as build
/// args, which is the only point at which they can reach the bundle.
/// </para>
/// </summary>
public static class SsrFrontendDockerfile
{
    /// <summary>The port Node frontends listen on by default, and what Coolify's proxy routes to.</summary>
    public const int ContainerPort = 3000;

    private const int DefaultNodeMajor = 22;

    /// <summary>
    /// Prefixes whose values a frontend build compiles into the bundle. Only these are emitted as
    /// build args: a secret has no business in a browser bundle, and anything the server reads at
    /// runtime is already supplied by the container environment.
    /// </summary>
    private static readonly string[] PublicEnvPrefixes =
        ["NEXT_PUBLIC_", "NUXT_PUBLIC_", "PUBLIC_", "VITE_", "REACT_APP_", "GATSBY_"];

    /// <param name="packageJsonContent">Used to pick the Node major from <c>engines.node</c> and to
    /// tell whether a lockfile-based install is safe.</param>
    /// <param name="hasLockfile"><c>npm ci</c> requires a lockfile and fails without one.</param>
    /// <param name="buildTimeEnvKeys">Keys the app's build inlines; non-public ones are ignored.</param>
    /// <param name="installCommand">The repo's own install command when detection found one; it
    /// reflects how the project is actually built, so it wins over anything inferred here.</param>
    public static string Build(
        string? packageJsonContent,
        bool hasLockfile,
        IReadOnlyList<string>? buildTimeEnvKeys = null,
        string? buildCommand = null,
        string? startCommand = null,
        string? installCommand = null)
    {
        var nodeMajor = ResolveNodeMajorOrDefault(packageJsonContent);
        var install = ResolveInstallCommand(installCommand, hasLockfile);
        var build = string.IsNullOrWhiteSpace(buildCommand) ? "npm run build" : buildCommand.Trim();
        var start = string.IsNullOrWhiteSpace(startCommand) ? "npm run start" : startCommand.Trim();

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by DeployAI. Coolify's Nixpacks build receives none of the app's");
        builder.AppendLine("# environment, so public values a frontend inlines at build time are declared as");
        builder.AppendLine("# build args below — without them the bundle keeps its source fallback (localhost).");
        builder.AppendLine($"FROM node:{nodeMajor}-alpine AS build");
        builder.AppendLine("WORKDIR /app");
        // Dependencies are copied first so an unchanged manifest keeps the install layer cached.
        builder.AppendLine("COPY package.json package-lock.json* ./");
        builder.AppendLine($"RUN {install}");
        builder.AppendLine("COPY . .");

        foreach (var key in ResolvePublicKeys(buildTimeEnvKeys))
        {
            // ARG declares it; ENV makes it visible to the build command's process, which is what
            // the framework actually reads. Values are supplied by the builder at build time.
            builder.AppendLine($"ARG {key}");
            builder.AppendLine($"ENV {key}=${key}");
        }

        builder.AppendLine($"RUN {build}");
        builder.AppendLine();
        builder.AppendLine($"FROM node:{nodeMajor}-alpine");
        builder.AppendLine("WORKDIR /app");
        builder.AppendLine("ENV NODE_ENV=production");
        // The whole built tree is carried over rather than a standalone bundle: `output: "standalone"`
        // is opt-in per project, and copying everything works whether or not it is enabled.
        builder.AppendLine("COPY --from=build /app ./");
        builder.AppendLine($"ENV PORT={ContainerPort}");
        builder.AppendLine($"EXPOSE {ContainerPort}");
        builder.Append($"CMD {ToExecForm(start)}");

        return builder.ToString();
    }

    /// <summary>
    /// <c>npm ci</c> is the reproducible install, but it refuses to run when package-lock.json has
    /// drifted from package.json — a common state in real repos, and one Nixpacks never surfaced
    /// because it used <c>npm install</c>. Falling back keeps a drifted lockfile from turning a
    /// working deploy into a build failure, while still preferring the locked install when it holds.
    /// </summary>
    public static string ResolveInstallCommand(string? installCommand, bool hasLockfile)
    {
        if (!string.IsNullOrWhiteSpace(installCommand))
        {
            return installCommand.Trim();
        }

        return hasLockfile ? "npm ci || npm install" : "npm install";
    }

    /// <summary>
    /// Reads <c>engines.node</c> (e.g. "&gt;=22.12.0") so the image satisfies what the framework
    /// requires — Next 16 refuses older Node, and a mismatch only surfaces as an install warning.
    /// </summary>
    /// <summary>
    /// The Node major this app should be built on: what it asks for, or a current default.
    /// </summary>
    /// <remarks>
    /// Exposed because the same answer is needed outside the generated Dockerfile. Coolify's
    /// Nixpacks build defaults to Node 18 when a package.json declares no engines, which is older
    /// than Angular, Next and Vite now accept — so a repository that says nothing about Node fails
    /// its build on a version nobody chose. Coolify prints the remedy in the build log and expects a
    /// human to go and set NIXPACKS_NODE_VERSION; DeployAI can set it from here instead.
    /// </remarks>
    public static int ResolveNodeMajorOrDefault(string? packageJsonContent) =>
        ResolveNodeMajor(packageJsonContent) ?? DefaultNodeMajor;

    public static int? ResolveNodeMajor(string? packageJsonContent)
    {
        if (string.IsNullOrWhiteSpace(packageJsonContent))
        {
            return null;
        }

        var match = Regex.Match(
            packageJsonContent,
            @"""engines""\s*:\s*\{[^}]*""node""\s*:\s*""[^""\d]*(\d+)",
            RegexOptions.IgnoreCase | RegexOptions.Singleline);

        return match.Success && int.TryParse(match.Groups[1].Value, out var major) ? major : null;
    }

    public static IReadOnlyList<string> ResolvePublicKeys(IReadOnlyList<string>? keys) =>
        (keys ?? [])
            .Where(key => !string.IsNullOrWhiteSpace(key))
            .Select(key => key.Trim())
            .Where(key => PublicEnvPrefixes.Any(prefix => key.StartsWith(prefix, StringComparison.Ordinal)))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(key => key, StringComparer.Ordinal)
            .ToList();

    /// <summary>
    /// Exec form avoids a shell wrapper, so the Node process is PID 1 and receives the stop signal
    /// instead of being killed after a timeout.
    /// </summary>
    private static string ToExecForm(string command)
    {
        var parts = command.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        return "[" + string.Join(", ", parts.Select(part => $"\"{part}\"")) + "]";
    }
}
