using DeployAI.Infrastructure.Adapters;
using DeployAI.Infrastructure.GitHub;

namespace DeployAI.Api.Services;

/// <summary>
/// Ensures a .NET server that Coolify's Nixpacks can't build (a modular monolith, or a .NET
/// version newer than Nixpacks' SDK) has a Dockerfile committed to the repo, so the app can be
/// created with the Dockerfile build pack instead. The Dockerfile is generated deterministically
/// and committed to the deployment branch as an additive artifact (idempotent: re-running upserts
/// it), so redeploys always build the current code.
/// </summary>
public interface IServerDockerfileProvisioner
{
    Task<ServerDockerfileResult?> EnsureDockerfileAsync(
        string githubToken,
        string owner,
        string repo,
        string branch,
        string rootDirectory,
        string? serviceDirectory,
        CancellationToken cancellationToken);

    /// <summary>
    /// Same idea for a server-rendered frontend, for a different reason: Coolify's Nixpacks build
    /// receives only its own NIXPACKS_*/COOLIFY_* variables, never the app's, so values the
    /// framework inlines at build time (NEXT_PUBLIC_*) never reach the bundle and it keeps the
    /// source's localhost fallback. Owning the Dockerfile is what lets them be passed as build args.
    /// </summary>
    Task<ServerDockerfileResult?> EnsureSsrWebsiteDockerfileAsync(
        string githubToken,
        string owner,
        string repo,
        string branch,
        string appDirectory,
        IReadOnlyList<string> buildTimeEnvKeys,
        string? buildCommand,
        string? startCommand,
        string? installCommand,
        CancellationToken cancellationToken);
}

/// <summary>The build directory (Coolify base directory) and the Dockerfile path relative to it.</summary>
public sealed record ServerDockerfileResult(string BaseDirectory, string DockerfileLocation, int ExposedPort);

public sealed class ServerDockerfileProvisioner : IServerDockerfileProvisioner
{
    private readonly IGitHubService _gitHubService;

    public ServerDockerfileProvisioner(IGitHubService gitHubService)
    {
        _gitHubService = gitHubService;
    }

    public async Task<ServerDockerfileResult?> EnsureDockerfileAsync(
        string githubToken,
        string owner,
        string repo,
        string branch,
        string rootDirectory,
        string? serviceDirectory,
        CancellationToken cancellationToken)
    {
        var buildRoot = Normalize(rootDirectory);
        var serviceDir = Normalize(serviceDirectory ?? rootDirectory);

        // Find the entry csproj in the service directory.
        var serviceContents = await _gitHubService.ListAllContentsAsync(
            githubToken, owner, repo, serviceDir, branch, cancellationToken);
        var csproj = serviceContents.FirstOrDefault(item =>
            string.Equals(item.Type, "file", StringComparison.OrdinalIgnoreCase) &&
            item.Name.EndsWith(".csproj", StringComparison.OrdinalIgnoreCase));
        if (csproj is null)
        {
            return null;
        }

        var csprojContent = await _gitHubService.GetFileContentAsync(
            githubToken, owner, repo, csproj.Path, branch, cancellationToken);

        var dockerfileContent = DotnetServerDockerfile.Build(buildRoot, serviceDir, csprojContent, csproj.Name);
        var dockerfilePath = string.IsNullOrEmpty(buildRoot) ? "Dockerfile" : $"{buildRoot}/Dockerfile";

        // Idempotent: if a Dockerfile is already there, update it (needs the blob sha).
        var existing = await _gitHubService.GetFileMetadataAsync(
            githubToken, owner, repo, dockerfilePath, branch, cancellationToken);

        await _gitHubService.UpsertFileAsync(
            githubToken,
            owner,
            repo,
            dockerfilePath,
            dockerfileContent,
            "Add Dockerfile for Coolify deployment (generated by DeployAI)",
            branch,
            existing?.Sha,
            cancellationToken);

        // Coolify's dockerfile_location is relative to the base directory (the build root).
        return new ServerDockerfileResult(
            BaseDirectory: buildRoot,
            DockerfileLocation: "/Dockerfile",
            ExposedPort: DotnetServerDockerfile.ContainerPort);
    }

    public async Task<ServerDockerfileResult?> EnsureSsrWebsiteDockerfileAsync(
        string githubToken,
        string owner,
        string repo,
        string branch,
        string appDirectory,
        IReadOnlyList<string> buildTimeEnvKeys,
        string? buildCommand,
        string? startCommand,
        string? installCommand,
        CancellationToken cancellationToken)
    {
        var appDir = Normalize(appDirectory);

        // The build context is the app directory, so its package.json is what the image installs.
        // No package.json means this isn't a Node app and generating a Dockerfile would only
        // produce a confusing build failure.
        var packageJsonPath = string.IsNullOrEmpty(appDir) ? "package.json" : $"{appDir}/package.json";
        var packageJson = await _gitHubService.GetFileContentAsync(
            githubToken, owner, repo, packageJsonPath, branch, cancellationToken);
        if (string.IsNullOrWhiteSpace(packageJson))
        {
            return null;
        }

        var lockPath = string.IsNullOrEmpty(appDir) ? "package-lock.json" : $"{appDir}/package-lock.json";
        var hasLockfile = !string.IsNullOrWhiteSpace(await _gitHubService.GetFileContentAsync(
            githubToken, owner, repo, lockPath, branch, cancellationToken));

        var dockerfileContent = SsrFrontendDockerfile.Build(
            packageJson,
            hasLockfile,
            buildTimeEnvKeys,
            buildCommand,
            startCommand,
            installCommand);

        var dockerfilePath = string.IsNullOrEmpty(appDir) ? "Dockerfile" : $"{appDir}/Dockerfile";
        var existing = await _gitHubService.GetFileMetadataAsync(
            githubToken, owner, repo, dockerfilePath, branch, cancellationToken);

        // Idempotent, and skipped entirely when the content already matches so redeploys don't
        // pile up no-op commits on the branch.
        if (existing is not null && ContentMatches(existing.Content, dockerfileContent))
        {
            return new ServerDockerfileResult(appDir, "/Dockerfile", SsrFrontendDockerfile.ContainerPort);
        }

        await _gitHubService.UpsertFileAsync(
            githubToken,
            owner,
            repo,
            dockerfilePath,
            dockerfileContent,
            "Add Dockerfile for Coolify deployment (generated by DeployAI)",
            branch,
            existing?.Sha,
            cancellationToken);

        return new ServerDockerfileResult(appDir, "/Dockerfile", SsrFrontendDockerfile.ContainerPort);
    }

    /// <summary>
    /// GitHub returns file contents base64-encoded (and line-wrapped), so compare the decoded text
    /// with line endings normalised rather than the raw payloads.
    /// </summary>
    private static bool ContentMatches(string? encodedContent, string desired)
    {
        if (string.IsNullOrWhiteSpace(encodedContent))
        {
            return false;
        }

        try
        {
            var decoded = System.Text.Encoding.UTF8.GetString(
                Convert.FromBase64String(encodedContent.Replace("\n", string.Empty)));
            return string.Equals(
                decoded.Replace("\r\n", "\n").TrimEnd(),
                desired.Replace("\r\n", "\n").TrimEnd(),
                StringComparison.Ordinal);
        }
        catch (FormatException)
        {
            return false;
        }
    }

    private static string Normalize(string? path) =>
        path?.Trim().Replace('\\', '/').Trim('/') ?? string.Empty;
}
