using DeployAI.Infrastructure.Adapters;
using DeployAI.Infrastructure.GitHub;

namespace DeployAI.Api.Services;

/// <summary>
/// Ensures a .NET server that Coolify's Nixpacks can't build (a modular monolith, or a .NET
/// version newer than Nixpacks' SDK) has a Dockerfile committed to the repo, so the app can be
/// created with the Dockerfile build pack instead. The Dockerfile is generated deterministically
/// and committed to the deployment branch as an additive artifact (idempotent: re-running upserts
/// it), so redeploys always build the current code.
/// </summary>
public interface IServerDockerfileProvisioner
{
    Task<ServerDockerfileResult?> EnsureDockerfileAsync(
        string githubToken,
        string owner,
        string repo,
        string branch,
        string rootDirectory,
        string? serviceDirectory,
        CancellationToken cancellationToken);
}

/// <summary>The build directory (Coolify base directory) and the Dockerfile path relative to it.</summary>
public sealed record ServerDockerfileResult(string BaseDirectory, string DockerfileLocation);

public sealed class ServerDockerfileProvisioner : IServerDockerfileProvisioner
{
    private readonly IGitHubService _gitHubService;

    public ServerDockerfileProvisioner(IGitHubService gitHubService)
    {
        _gitHubService = gitHubService;
    }

    public async Task<ServerDockerfileResult?> EnsureDockerfileAsync(
        string githubToken,
        string owner,
        string repo,
        string branch,
        string rootDirectory,
        string? serviceDirectory,
        CancellationToken cancellationToken)
    {
        var buildRoot = Normalize(rootDirectory);
        var serviceDir = Normalize(serviceDirectory ?? rootDirectory);

        // Find the entry csproj in the service directory.
        var serviceContents = await _gitHubService.ListAllContentsAsync(
            githubToken, owner, repo, serviceDir, branch, cancellationToken);
        var csproj = serviceContents.FirstOrDefault(item =>
            string.Equals(item.Type, "file", StringComparison.OrdinalIgnoreCase) &&
            item.Name.EndsWith(".csproj", StringComparison.OrdinalIgnoreCase));
        if (csproj is null)
        {
            return null;
        }

        var csprojContent = await _gitHubService.GetFileContentAsync(
            githubToken, owner, repo, csproj.Path, branch, cancellationToken);

        var dockerfileContent = DotnetServerDockerfile.Build(buildRoot, serviceDir, csprojContent, csproj.Name);
        var dockerfilePath = string.IsNullOrEmpty(buildRoot) ? "Dockerfile" : $"{buildRoot}/Dockerfile";

        // Idempotent: if a Dockerfile is already there, update it (needs the blob sha).
        var existing = await _gitHubService.GetFileMetadataAsync(
            githubToken, owner, repo, dockerfilePath, branch, cancellationToken);

        await _gitHubService.UpsertFileAsync(
            githubToken,
            owner,
            repo,
            dockerfilePath,
            dockerfileContent,
            "Add Dockerfile for Coolify deployment (generated by DeployAI)",
            branch,
            existing?.Sha,
            cancellationToken);

        // Coolify's dockerfile_location is relative to the base directory (the build root).
        return new ServerDockerfileResult(
            BaseDirectory: buildRoot,
            DockerfileLocation: "/Dockerfile");
    }

    private static string Normalize(string? path) =>
        path?.Trim().Replace('\\', '/').Trim('/') ?? string.Empty;
}
