// <auto-generated />
using System;
using DeployAI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeployAI.Data.Migrations
{
    [DbContext(typeof(DeployAIDbContext))]
    [Migration("20260706163618_AddDeploymentTargetFailureAnalysis")]
    partial class AddDeploymentTargetFailureAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeployAI.Data.Entities.DeployTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId");

                    b.HasIndex("ProjectId");

                    b.ToTable("deploy_targets", (string)null);
                });

            modelBuilder.Entity("DeployAI.Data.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GitCommitMessage")
                        .HasColumnType("text");

                    b.Property<string>("GitCommitSha")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("DeployAI.Data.Entities.DeploymentLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DeploymentTargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentTargetId", "Sequence");

                    b.ToTable("deployment_logs", (string)null);
                });

            modelBuilder.Entity("DeployAI.Data.Entities.DeploymentTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeployTargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeployUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureAnalysisJson")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDeploymentId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeployTargetId");

                    b.HasIndex("DeploymentId");

                    b.ToTable("deployment_targets", (string)null);
                });

            modelBuilder.Entity("DeployAI.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeploymentSetupJson")
                        .HasColumnType("text");

                    b.Property<string>("EnvironmentSyncJson")
                        .HasColumnType("text");

                    b.Property<string>("GitHubRepoFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("DeployAI.Data.Entities.ProviderCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("TokenEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ProviderName", "Label")
                        .IsUnique();

                    b.ToTable("provider_credentials", (string)null);
                });

            modelBuilder.Entity("DeployAI.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("DeployAI.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint");

                    b.Property<string>("GitHubLogin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("GitHubTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DeployAI.Data.Entities.DeployTarget", b =>
                {
                    b.HasOne("DeployAI.Data.Entities.ProviderCredential", "Credential")
                        .WithMany("DeployTargets")
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeployAI.Data.Entities.Project", "Project")
                        .WithMany("DeployTargets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DeployAI.Data.Entities.Deployment", b =>
                {
                    b.HasOne("DeployAI.Data.Entities.Project", "Project")
                        .WithMany("Deployments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DeployAI.Data.Entities.DeploymentLog", b =>
                {
                    b.HasOne("DeployAI.Data.Entities.DeploymentTarget", "DeploymentTarget")
                        .WithMany("Logs")
                        .HasForeignKey("DeploymentTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeploymentTarget");
                });

            modelBuilder.Entity("DeployAI.Data.Entities.DeploymentTarget", b =>
                {
                    b.HasOne("DeployAI.Data.Entities.DeployTarget", "DeployTarget")
                        .WithMany("DeploymentTargets")
                        .HasForeignKey("DeployTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeployAI.Data.Entities.Deployment", "Deployment")
                        .WithMany("Targets")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeployTarget");

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("DeployAI.Data.Entities.Project", b =>
                {
                    b.HasOne("DeployAI.Data.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeployAI.Data.Entities.ProviderCredential", b =>
                {
                    b.HasOne("DeployAI.Data.Entities.User", "User")
                        .WithMany("ProviderCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeployAI.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("DeployAI.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeployAI.Data.Entities.DeployTarget", b =>
                {
                    b.Navigation("DeploymentTargets");
                });

            modelBuilder.Entity("DeployAI.Data.Entities.Deployment", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("DeployAI.Data.Entities.DeploymentTarget", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("DeployAI.Data.Entities.Project", b =>
                {
                    b.Navigation("DeployTargets");

                    b.Navigation("Deployments");
                });

            modelBuilder.Entity("DeployAI.Data.Entities.ProviderCredential", b =>
                {
                    b.Navigation("DeployTargets");
                });

            modelBuilder.Entity("DeployAI.Data.Entities.User", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("ProviderCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
