using DeployAI.Core.Deployments.Graph;

namespace DeployAI.Core.Deployments.Planning;

/// <summary>
/// Orders operations for a compose deployment on Coolify. This is where deployment *knowledge*
/// lives, separated from rendering — and separated from the UI, where this exact sequence was
/// previously hardcoded in wizard orchestration.
///
/// The ordering is not stylistic; each constraint was established against a live instance:
/// - Env vars go before the first deploy, so the app boots configured instead of crash-looping
///   on missing secrets (a .NET seed step throws without them; nginx then answers 502).
/// - The domain goes *after* the first deploy: Coolify rejects docker_compose_domains until a
///   deploy has parsed the compose file into docker_compose_raw, and that field cannot be set
///   through the API at all ("This field is not allowed" on both create and update).
/// - A redeploy follows the domain, because Traefik's route only materializes on deploy.
/// </summary>
public sealed class CoolifyComposePlanner : IDeploymentPlanner
{
    public string Target => "coolify-compose";

    public DeploymentExecutionPlan Plan(DeploymentGraph graph, ProviderStateSnapshot state)
    {
        var steps = new List<DeploymentStep>();

        // Buckets first: their keys are among the env values the app needs at first boot.
        foreach (var bucket in graph.WithCapability(ServiceCapability.ObjectStorage))
        {
            steps.Add(new ProvisionBucketStep(
                bucket.Id,
                Reuse: state.Buckets.Contains(bucket.Id, StringComparer.OrdinalIgnoreCase)));
        }

        steps.Add(new EnsureApplicationStep(Reuse: state.ApplicationExists));

        // Every deployable node's requirements plus the keys its ConnectsTo edges impose.
        foreach (var service in graph.Services.Where(s => s.Capabilities.IsDeployable()))
        {
            var keys = service.Env.Select(env => env.Name)
                .Concat(graph.EdgesFrom<ConnectsToEdge>(service.Id).SelectMany(e => e.EnvMapping.Keys))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToArray();

            if (keys.Length > 0)
            {
                steps.Add(new SetEnvVarsStep(service.Id, keys));
            }
        }

        steps.Add(new DeployStep(Ordinal: 1));

        // Only custom domains need the assign+redeploy tail; an autogenerated domain is
        // attached by Coolify itself, and one already assigned needs nothing.
        var pendingDomains = state.DomainAssigned
            ? []
            : graph.Ingress.Where(rule => !string.IsNullOrWhiteSpace(rule.Domain)).ToList();

        if (pendingDomains.Count > 0)
        {
            foreach (var rule in pendingDomains)
            {
                steps.Add(new AssignDomainStep(rule));
            }

            steps.Add(new DeployStep(Ordinal: 2));
        }

        return new DeploymentExecutionPlan(steps);
    }
}
